OnlineShop/OnlineShopWebApp/Models/DiscountViewModel.cs
using System.Collections.Generic;

namespace OnlineShopWebApp.Models
{
    public class DiscountViewModel
    {
        public int Id { get; set; }

        public List<ProductViewModel> Products { get; set; }
        public int DiscountPercent { get; set; }
        
    }
}

OnlineShop/OnlineShopWebApp/Models/EditProductDiscountViewModel.cs
using System.Collections.Generic;

namespace OnlineShopWebApp.Models
{
    public class EditProductDiscountViewModel
    {
        public ProductViewModel Product { get; set; }
        public DiscountViewModel Discount { get; set; }
        public List<DiscountViewModel> Discounts { get; set; }

    }
}

OnlineShop/OnlineShopWebApp/Areas/Admin/Controllers/DiscountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DB.Interfaces;
using OnlineShop.DB.Models;
using OnlineShop.DB.Models.Enumerations;
using OnlineShop.DB.Models.Interfaces;
using OnlineShopWebApp.Helpers;
using OnlineShopWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using AutoMapper;
using OnlineShop.DB.Patterns;

namespace OnlineShopWebApp.Areas.Admin.Controllers
{
    [Area(Constants.AdminRoleName)]
    [Authorize(Roles = $"{Constants.AdminRoleName}, {Constants.ModeratorRoleName}")]
    public class DiscountController : Controller
    {        
        private readonly UserManager<User> _userManager;
        private readonly IMapper _mapping;
        private readonly IUnitOfWork _unitOfWork;
        public DiscountController(UserManager<User> userManager, IMapper mapping, IUnitOfWork unitOfWork)
        {
            _userManager = userManager;
            _mapping = mapping;
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> NoDiscountProducts()
        {
            var products = _mapping.Map<List<ProductViewModel>>((await _unitOfWork.DiscountsDbStorage.GetProductsWithOutDiscountAsync()));
            return View(products);
        }

        public async Task<IActionResult> ProductDiscountInfo(int productId, int discountId)
        {
            var product = _mapping.Map<ProductViewModel>((await _unitOfWork.ProxyProductsDbStorage.TryGetByIdAsync(productId)));
            ViewBag.Product = product;
            var discount = _mapping.Map<DiscountViewModel>((await _unitOfWork.DiscountsDbStorage.TryGetByIdAsync(discountId)));
            return View(discount);
        }

        public async Task<IActionResult> SortedDiscounts(int discountId)
        {
            ViewBag.Discount = _mapping.Map<DiscountViewModel>((await _unitOfWork.DiscountsDbStorage.TryGetByIdAsync(discountId)));
            var discounts = _mapping.Map<List<DiscountViewModel>>((await _unitOfWork.DiscountsDbStorage.GetAllAsync()));
            return View(discounts);
        }
        public async Task<IActionResult> DiscountProducts()
        {
            var discounts = await _unitOfWork.DiscountsDbStorage.GetAllAsync();
            var discountsView = _mapping.Map<List<DiscountViewModel>>(discounts);
            return View(discountsView);
        }

        public async Task<IActionResult> RemoveProductDiscount(int prodId, int discountId)
        {
            var product = await _unitOfWork.ProxyProductsDbStorage.TryGetByIdAsync(prodId);
            await _unitOfWork.DiscountsDbStorage.RemoveDiscountAsync(product, discountId);
            await _unitOfWork.SaveChangesAsync();
            return RedirectToAction("DiscountProducts");
        }

        public async Task<IActionResult> MakeDiscount(int prodId)
        {
            var product = _mapping.Map<ProductViewModel>((await _unitOfWork.ProxyProductsDbStorage.TryGetByIdAsync(prodId)));
            ViewBag.Product = product;
            var discounts = _mapping.Map<List<DiscountViewModel>>((await _unitOfWork.DiscountsDbStorage.GetAllAsync()));
            return View(discounts);
        }

        [HttpPost]
        public async Task<ActionResult> MakeDiscountAsync(int productId, string discountDescription, int discountId)
        {
            if (ModelState.IsValid)
            {
                var discount = await _unitOfWork.DiscountsDbStorage.TryGetByIdAsync(discountId);
                var product = await _unitOfWork.ProxyProductsDbStorage.TryGetByIdAsync(productId);
                await _unitOfWork.DiscountsDbStorage.AddAsync(product, discount, discountDescription);
                await _unitOfWork.SaveChangesAsync();
            }
            return Redirect($"ProductDiscountInfo?productId={productId}&discountId={discountId}");
        }

        public async Task<IActionResult> EditProductDiscount(int productId, int discountId)
        {
            var product = await _unitOfWork.ProxyProductsDbStorage.TryGetByIdAsync(productId);
            var discount = await _unitOfWork.DiscountsDbStorage.TryGetByIdAsync(discountId);
            var discounts = await _unitOfWork.DiscountsDbStorage.GetAllAsync();
            var editView = new EditProductDiscountViewModel
            {
                Product = _mapping.Map<ProductViewModel>(product),
                Discount = _mapping.Map<DiscountViewModel>(discount),
                Discounts = _mapping.Map<List<DiscountViewModel>>(discounts)
            };
            return View(editView);
        }

        [HttpPost]
        public async Task<ActionResult> EditProductDiscountAsync(int productId, string discountDescription, int oldDiscountId, int newDiscountId)
        {
            if (ModelState.IsValid)
            {
                var product = await _unitOfWork.ProxyProductsDbStorage.TryGetByIdAsync(productId);
                await _unitOfWork.DiscountsDbStorage.ChangeDiscountAsync(product, oldDiscountId, newDiscountId, discountDescription);
                await _unitOfWork.SaveChangesAsync();
            }
            return RedirectToAction(nameof(ProductDiscountInfo), new {productId=productId, discountId=newDiscountId});
        }
    }
}

OnlineShop/OnlineShopWebApp/Areas/Admin/Views/Discount/DiscountProducts.cshtml
@model List<DiscountViewModel>

<div class="row">
    @await Html.PartialAsync("AdminMenu")
    <div class="col-9">
        @if (Model.All(x => x.Products == null) || Model.All(x => x.Products.Count == 0))
        {
            <h3>Продуктов со скидками не обнаружено!<a asp-area="Admin" asp-controller="Discount" asp-action="NoDiscountProducts"> Добавить?</a></h3>
        }
        else
        {
            <div class="row">
                <div class="col-auto mb-3">
                    <div class="btn-group">                        
                        <div class="dropdown">
                            <a class="btn btn-outline-info btn-sm mr-3" asp-area="Admin" asp-controller="Discount" asp-action="NoDiscountProducts">Добавить скидки</a>
                            <button class="btn btn-outline-success btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Отсортировать
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                @foreach (var discount in Model)
                                {
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Discount" asp-action="SortedDiscounts" asp-route-discountId="@discount.Id">@discount.DiscountPercent%</a>
                                }
                            </div>
                        </div>
                    </div>                   
                </div>
            </div>
            <h3>Сортировка по критерию: Все скидки</h3>
            <table class="table table-borderless text-center">
                <thead>
                    <tr>
                        <th>Изображение</th>
                        <th>Название</th>
                        <th>Описание акции</th>
                        <th>Скидка, %</th>
                        <th>Цена, грн</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var discount in Model)
                    {
                        if (discount.Products != null || discount.Products.Count != 0)
                        {
                            foreach (var product in discount.Products)
                            {
                                <tr>
                                    <td style="vertical-align:middle">
                                        <a asp-area="Admin" asp-controller="Discount" asp-action="ProductDiscountInfo" asp-route-productId="@product.Id" asp-route-discountId="@discount.Id"><img class="img-fluid" width="100" src="@product.Picture.Path"></a>
                                    </td>
                                    <td style="vertical-align:middle">
                                        <a asp-area="Admin" asp-controller="Discount" asp-action="ProductDiscountInfo" asp-route-productId="@product.Id" asp-route-discountId="@discount.Id">@product.Name</a>
                                    </td>
                                    <td style="vertical-align:middle">@product.DiscountDescription</td>
                                    <td style="vertical-align:middle">@discount.DiscountPercent</td>
                                    <td style="vertical-align:middle">@product.DiscountCost</td>
                                </tr>
                            }
                        }
                    }
                </tbody>
            </table>
        }
    </div>
</div>

OnlineShop/OnlineShopWebApp/Areas/Admin/Views/Discount/EditProductDiscount.cshtml
@model EditProductDiscountViewModel

<div class="row">
    @await Html.PartialAsync("AdminMenu")
    <div class="col-9">
        <form method="post">
            <div class="row">
                <div class="col-5">
                    <img class="img-fluid" src="@Model.Product.Picture.Path" />
                </div>
                <div class="col-7">
                    <input hidden="hidden" name="productId" value="@Model.Product.Id" />
                    <input hidden="hidden" name="oldDiscountId" value="@Model.Discount.Id" />
                    <div class="form-group">
                        <label class="badge badge-light" style="font-size:medium" for="Categori">Категория</label>
                        <input id="Categori" type="text" readonly="readonly" class="border-0 bg-transparent pl-0 form-control" value="@EnumHelper.GetDisplayName(Model.Product.Category)" />
                    </div>
                    <div class="form-group">
                        <label for="Brand" style="font-size:medium" class="badge badge-light">Брэнд</label>
                        <input id="Brand" type="text" readonly="readonly" class="border-0 bg-transparent pl-0 form-control" value="@Model.Product.Brand" />
                    </div>
                    <div class="form-group">
                        <label for="Name" style="font-size:medium" class="badge badge-light">Название</label>
                        <input id="Name" type="text" readonly="readonly" class="border-0 bg-transparent pl-0 form-control" value="@Model.Product.Name" />
                    </div>
                    <div class="form-group">
                        <label for="Description" style="font-size:medium" class="badge badge-light">Описание акции</label>
                        <input id="Description" value="@Model.Product.DiscountDescription" class="form-control pl-0" type="text" name="discountDescription" placeholder="(не обязательно)" />
                    </div>
                    <div class="form-group form-inline">
                        <label for="Discounts">Скидка, %</label>
                        <select class="btn btn-outline-secondary form-control btn-sm ml-2" name="newDiscountId" id="Discounts">
                            @foreach (var discount in Model.Discounts)
                            {
                                @if (discount.Id == Model.Discount.Id)
                                {
                                    <option value="@discount.Id" selected="selected">@discount.DiscountPercent</option>
                                }
                                else
                                {
                                    <option value="@discount.Id">@discount.DiscountPercent</option>
                                }
                            }
                        </select>
                    </div>
                    <button class="btn btn-warning btn-block mt-2" type="submit" asp-area="Admin" asp-controller="Discount" asp-action="EditProductDiscount">Сохранить</button>
                </div>
            </div>
        </form>
    </div>
</div>

OnlineShop/OnlineShopWebApp/Areas/Admin/Views/Discount/MakeDiscount.cshtml
@model List<DiscountViewModel>

<div class="row">
    @await Html.PartialAsync("AdminMenu")
    <div class="col-9">
        <form method="post">
            <div class="row">
                <div class="col-5">
                    <img class="img-fluid" src="@ViewBag.Product.Picture.Path" />
                </div>
                <div class="col-7">                    
                    <div class="form-group">
                        <label for="Brand" style="font-size:large" class="badge badge-primary">Брэнд</label>
                        <input id="Brand" type="text" readonly="readonly" class="border-0 bg-transparent pl-0 form-control" value="@ViewBag.Product.Brand" />
                    </div>
                    <div class="form-group">
                        <label for="Name" style="font-size:large" class="badge badge-primary">Название</label>
                        <input id="Name" type="text" readonly="readonly" class="border-0 bg-transparent pl-0 form-control" value="@ViewBag.Product.Name" />
                    </div>
                    <div class="form-group">
                        <label for="Description" style="font-size:large" class="badge badge-primary">Описание акции</label>
                        <textarea id="Description" class="h-100 form-control pl-0" type="text" name="discountDescription" placeholder="(не обязательно)"></textarea>
                    </div>
                    <div class="form-group form-inline">
                        <label for="Discounts">Скидка, %</label>
                        <select class="btn btn-outline-secondary form-control btn-sm ml-2" name="discountId" id="Discounts">
                            @foreach (var discount in Model)
                            {
                                @if (Model.IndexOf(discount) == 0)
                                {
                                    <option value="@discount.Id" selected="selected">@discount.DiscountPercent</option>
                                }
                                else
                                {
                                    <option value="@discount.Id">@discount.DiscountPercent</option>
                                }
                            }
                        </select>
                    </div>
                    <button class="btn btn-warning btn-block mt-2" type="submit" asp-area="Admin" asp-controller="Discount" asp-action="MakeDiscount" asp-route-productId="@ViewBag.Product.Id">Сохранить</button>
                </div>
            </div>
        </form>
    </div>
</div>

OnlineShop/OnlineShopWebApp/Areas/Admin/Views/Discount/NoDiscountProducts.cshtml
@model List<ProductViewModel>

<div class="row">
    @await Html.PartialAsync("AdminMenu")
    <div class="col-9">
        <h2>Список продуктов без скидок</h2><br />
        <table class="table table-hover text-center">
            <thead>
                <tr>
                    <th>Изображение</th>
                    <th>Категория</th>
                    <th>Брэнд</th>
                    <th>Название</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var product in Model)
                {
                    <tr>
                        <td style="vertical-align:middle">
                            <img src="@product.Picture.Path" width="100">
                        </td>
                        <td style="vertical-align:middle">@product.Category</td>
                        <td style="vertical-align:middle">@product.Brand </td>
                        <td style="vertical-align:middle">@product.Name</td>
                        <td style="vertical-align:middle">
                            <a class="btn btn-block btn-secondary" asp-area="Admin" asp-controller="Discount" asp-action="MakeDiscount" asp-route-prodId="@product.Id">Скидки</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

OnlineShop/OnlineShopWebApp/Areas/Admin/Views/Discount/ProductDiscountInfo.cshtml
@model DiscountViewModel
<div class="row">
    @await Html.PartialAsync("AdminMenu")
    <div class="col-9">
        <div class="row">
            <div class="col-5">
                <img class="img-fluid" src="@ViewBag.Product.Picture.Path" />
            </div>
            <div class="col-7">
                <div class="form-group">
                    <label class="badge badge-light text-dark" style="font-size:medium" for="Categori">Категория:</label>
                    <input id="Categori" style="width:400px" type="text" readonly="readonly" class="border-0 bg-transparent" value="@EnumHelper.GetDisplayName(ViewBag.Product.Category)" />
                </div>
                <div class="form-group">
                    <label class="badge badge-light text-dark" style="font-size:medium" for="Brand">Брэнд:</label>
                    <input id="Brand" style="width:400px" type="text" readonly="readonly" class="border-0 bg-transparent" value="@ViewBag.Product.Brand" />
                </div>
                <div class="form-group">
                    <label class="badge badge-light text-dark" style="font-size:medium" for="Name">Название:</label>
                    <input id="Name" style="width:400px" type="text" readonly="readonly" class="border-0 bg-transparent" value="@ViewBag.Product.Name" />
                </div>
                <div class="form-group">
                    <label class="badge badge-light text-dark" style="font-size:medium" for="Description">Описание акции:</label>
                    <input id="Description" style="width:400px" type="text" readonly="readonly" class="border-0 bg-transparent" value="@ViewBag.Product.DiscountDescription" />
                </div>
                <div class="form-group form-inline">
                    <label class="badge badge-light text-dark" style="font-size:medium" for="Discount">Скидка:</label>
                    <input id="Discount" type="text" readonly="readonly" class="border-0 bg-transparent ml-2" value="@Model.DiscountPercent%" />
                </div>
                <div class="form-group form-inline">
                    <label class="badge badge-light text-dark" style="font-size:medium" for="Cost">Цена со скидкой, грн:</label>
                    <input id="Cost" type="text" readonly="readonly" class="border-0 bg-transparent ml-2" value="@ViewBag.Product.DiscountCost" />
                </div>
                <a class="btn btn-warning mt-2 float-left" asp-area="Admin" asp-controller="Discount" asp-action="EditProductDiscount" asp-route-productId="@ViewBag.Product.Id" asp-route-discountId="@Model.Id">Изменить скидку</a>
                <a class="btn btn-danger mt-2 float-right" asp-area="Admin" asp-controller="Discount" asp-action="RemoveProductDiscount" asp-route-prodId="@ViewBag.Product.Id" asp-route-discountId="@Model.Id">Убрать скидку</a>
            </div>
        </div>
    </div>
</div>

OnlineShop/OnlineShopWebApp/Areas/Admin/Views/Discount/SortedDiscounts.cshtml
@model List<DiscountViewModel>

@{
    DiscountViewModel discountView = @ViewBag.Discount;
}
<div class="row">
    @await Html.PartialAsync("AdminMenu")
    <div class="col-9">
        <div class="row">
            <div class="col-auto mb-3">
                <div class="btn-group">
                    <div class="dropdown">
                        <a class="btn btn-outline-info btn-sm mr-3" asp-area="Admin" asp-controller="Discount" asp-action="NoDiscountProducts">Добавить скидки</a>
                        <button class="btn btn-outline-success btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Отсортировать
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            @foreach (var discount in Model)
                            {
                                if (discountView.Id == discount.Id)
                                {
                                    <a class="dropdown-item disabled" asp-area="Admin" asp-controller="Discount" asp-action="SortedDiscounts" asp-route-discountId="@discount.Id">@discount.DiscountPercent%</a>
                                }
                                else
                                {
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Discount" asp-action="SortedDiscounts" asp-route-discountId="@discount.Id">@discount.DiscountPercent%</a>
                                }
                            }
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Discount" asp-action="DiscountProducts">Все скидки</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <h3>Сортировка по критерию: @discountView.DiscountPercent%</h3>
        <table class="table table-borderless text-center">
            <thead>
                <tr>
                    <th>Изображение</th>
                    <th>Название</th>
                    <th>Описание акции</th>
                    <th>Скидка, %</th>
                    <th>Цена, грн</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var product in discountView.Products)
                {
                    <tr>
                        <td style="vertical-align:middle">
                            <a asp-area="Admin" asp-controller="Discount" asp-action="ProductDiscountInfo" asp-route-productId="@product.Id" asp-route-discountId="@discountView.Id"><img class="img-fluid" width="100" src="@product.Picture.Path"></a>
                        </td>
                        <td style="vertical-align:middle">
                            <a asp-area="Admin" asp-controller="Discount" asp-action="ProductDiscountInfo" asp-route-productId="@product.Id" asp-route-discountId="@discountView.Id">@product.Name</a>
                        </td>
                        <td style="vertical-align:middle">@product.DiscountDescription</td>
                        <td style="vertical-align:middle">@discountView.DiscountPercent</td>
                        <td style="vertical-align:middle">@product.DiscountCost</td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>