OnlineShop/OnlineShopWebApp/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DB.Interfaces;
using OnlineShop.DB.Models;
using OnlineShop.DB.Models.Interfaces;
using OnlineShopWebApp.Helpers;
using OnlineShopWebApp.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using OnlineShopWebApp.Services;
using AutoMapper;
using System;
using Org.BouncyCastle.Bcpg;
using System.Linq;
using OnlineShop.DB.Patterns;

namespace OnlineShopWebApp.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<User> _userManager;
        private readonly EmailService _emailService;
        private readonly IMapper _mapping;

        public OrderController(UserManager<User> userManager, EmailService emailService, IMapper mapping, IUnitOfWork unitOfWork)
        {
            _userManager = userManager;
            _emailService = emailService;
            _mapping = mapping;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Confirmation()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> OrderingAsync(OrderViewModel order)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            var basketItems = (await _unitOfWork.ProxyBasketDbStorage.TryGetExistingByUserIdAsync(user.Id)).Items;

            var orderDb = _mapping.Map<OrderViewModel, Order>(order, opt =>
            {
                opt.AfterMap((src, dest) => dest.Items = basketItems);
                opt.BeforeMap((src, dest) => src.Id = Guid.NewGuid());
                opt.BeforeMap((src, dest) => src.OrderDateTime = DateTime.UtcNow.ToString());
            });

            var basketItemsView = _mapping.Map<List<BasketItemViewModel>>(basketItems);
            foreach(var item in basketItemsView)
            {
                item.Product.Flavor = item.Product.Flavors.First(x => x.Id == item.ProductInfo.FlavorId);
            }

            await _emailService.SendOrderConfirmEmailAsync(user.Email, basketItemsView);

            await _unitOfWork.ProxyProductsDbStorage.ReduceAmountInStock(orderDb.Items);
            await _unitOfWork.ClosedPurchasesDbStorage.SaveAsync(orderDb);
            await _unitOfWork.ProxyBasketDbStorage.CloseAsync(user.Id);
            await _unitOfWork.SaveChangesAsync();

            return Redirect(nameof(Confirmation));
        }
    }
}

OnlineShop/OnlineShopWebApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DB.Models;
using OnlineShop.DB.Models.Enumerations;
using OnlineShop.DB.Models.Interfaces;
using OnlineShopWebApp.Helpers;
using OnlineShopWebApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using AutoMapper;
using Microsoft.CodeAnalysis;
using OnlineShopWebApp.FeedbackApi.Models;
using OnlineShopWebApp.FeedbackApi;
using OnlineShop.DB.Patterns;
using OnlineShop.DB.Helpers;

namespace OnlineShopWebApp.Controllers
{
    public class ProductController : Controller
    {
        
        private readonly UserManager<User> _userManager;
        private readonly FeedbackApiClient _feedbackApiClient;
        private readonly IMapper _mapping;
        private const int pageProductsCount = 20;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ProductEqualityComparer _comparer;
        public ProductController(UserManager<User> userManager, FeedbackApiClient feedbackApiClient, IMapper mapping, IUnitOfWork unitOfWork)
        {
            _userManager = userManager;
            _feedbackApiClient = feedbackApiClient;
            _mapping = mapping;
            _unitOfWork = unitOfWork;
            _comparer = new ProductEqualityComparer();
        }
        public async Task<IActionResult> Index(int prodId)
        {
            var feedbacks = await _feedbackApiClient.GetFeedbacksAsync(prodId);
            var product = await _unitOfWork.ProxyProductsDbStorage.TryGetByIdAsync(prodId);

            var user = User.Identity.IsAuthenticated ? await _userManager.FindByNameAsync(User.Identity.Name) : null;

            var favoriteProducts = user != null ? await _unitOfWork.FavoriteProductsDbStorage.GetByUserIdAsync(user.Id) : null;

            if (product != null)
            {
                var productView = _mapping.Map<ProductViewModel>(product);
                productView.Feedbacks = _mapping.Map<List<FeedbackViewModel>>(feedbacks);

                if (favoriteProducts != null)
                {
                    if (favoriteProducts.Products.Any(x => _comparer.Equals(x, product)))
                    {
                        productView.isInFavorites = true;
                    }
                }

                return View(productView);
            }
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Authorize]
        public async Task<IActionResult> AddFavorite(int productId)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var product = await _unitOfWork.ProxyProductsDbStorage.TryGetByIdAsync(productId);
            await _unitOfWork.FavoriteProductsDbStorage.AddAsync(product, user.Id);

            await _unitOfWork.SaveChangesAsync();
            return RedirectToAction(nameof(Favorites));
        }

        [Authorize]
        public async Task<IActionResult> RemoveFavorite(int productId)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var product = await _unitOfWork.ProxyProductsDbStorage.TryGetByIdAsync(productId);
            await _unitOfWork.FavoriteProductsDbStorage.DeleteAsync(product, user.Id);
            await _unitOfWork.SaveChangesAsync();

            return RedirectToAction(nameof(Favorites));
        }

        [Authorize]
        public async Task<IActionResult> Favorites()
        {
            var userId = (await _userManager.FindByNameAsync(User.Identity.Name)).Id;
            var favorites = _mapping.Map<FavoriteProductViewModel>(await _unitOfWork.FavoriteProductsDbStorage.GetByUserIdAsync(userId));
            return View(favorites);
        }

        public async Task<IActionResult> DeleteFeedbackAsync(int feedbackId, int productId)
        {
            await _feedbackApiClient.DeleteAsync(feedbackId);
            return RedirectToAction(nameof(Index), new { prodId = productId });
        }

        [HttpPost]
        public async Task<IActionResult> AddFeedbackAsync(AddFeedbackModel feedbackModel)
        {
            feedbackModel.UserId = (await _userManager.FindByNameAsync(feedbackModel.Login)).Id;

            await _feedbackApiClient.AddAsync(feedbackModel);
            return RedirectToAction(nameof(Index), new { prodId = feedbackModel.ProductId });
        }

        [Authorize]
        public async Task<IActionResult> Comparing(int productId, int flavorId)
        {
            var userId = (await _userManager.FindByNameAsync(User.Identity.Name)).Id;
            var product = await _unitOfWork.ProxyProductsDbStorage.TryGetByIdAsync(productId);
            var flavor = await _unitOfWork.FlavorsDbStorage.TryGetByIdAsync(flavorId);
            await _unitOfWork.ComparingProductsDbStorage.AddAsync(userId, product, flavor);

            await _unitOfWork.SaveChangesAsync();
            return RedirectToAction(nameof(CheckComparer));
        }

        [Authorize]
        public async Task<IActionResult> Deleting(int prodId)
        {
            await _unitOfWork.ComparingProductsDbStorage.DeleteAsync(prodId);
            await _unitOfWork.SaveChangesAsync();

            return RedirectToAction(nameof(CheckComparer));
        }

        [Authorize]
        public async Task<IActionResult> CheckComparer()
        {
            var userId = (await _userManager.FindByNameAsync(User.Identity.Name)).Id;
            var comparingProducts = await _unitOfWork.ComparingProductsDbStorage.GetAllByUserIdAsync(userId);
            var comparingView = _mapping.Map<List<ComparingProductsViewModel>>(comparingProducts);
            return View(comparingView);
        }
        public async Task<IActionResult> CategoryProducts(int pageNumber = 1, ProductCategories category = ProductCategories.None)
        {
            var searchingProductsIds = ((int[])TempData["searchingProductsId"])?.First() == -1? new int[0] : ((int[])TempData["searchingProductsId"]);

            var searchingProducts = searchingProductsIds?.Select(x => _unitOfWork.ProxyProductsDbStorage.TryGetByIdAsync(x).Result).ToList();

            var products = searchingProducts ?? await _unitOfWork.ProxyProductsDbStorage.TryGetByCategoryAsync(category);

            if(products.Count== 0)
            {
                return View(new List<MainPageProductsViewModel>());
            }

            var productsView = _mapping.Map<List<Product>, List<MainPageProductsViewModel>>(products, opts =>
            {
                opts.AfterMap((src, dest) =>
                {
                    foreach (var product in dest)
                    {
                        product.PageNumber = (dest.IndexOf(product) + pageProductsCount) / pageProductsCount;
                    }
                });
            }).Where(x => x.PageNumber == pageNumber).ToList();

            var user = User.Identity.IsAuthenticated ? await _userManager.FindByNameAsync(User.Identity.Name) : null;

            var favoriteProducts = user != null ? await _unitOfWork.FavoriteProductsDbStorage.GetByUserIdAsync(user.Id) : null;

            foreach (var product in productsView)
            {
                product.Rating = await _feedbackApiClient.GetProductRetingAsync(product.Id);

                if (favoriteProducts != null)
                {
                    if (favoriteProducts.Products.Any(x => x.Id == product.Id))
                    {
                        product.IsInFavorites = true;
                    }
                }
            }

            ViewBag.PagesCount = products.Count() / pageProductsCount + 1;

            return View(productsView);
        }
        public async Task<IActionResult> BrandProducts(ProductBrands brand)
        {
            var products = await _unitOfWork.ProxyProductsDbStorage.TryGetByBrandAsync(brand);

            TempData["searchingProductsId"] = products.Count() == 0 ? new int[1] { -1 } : products.Select(x => x.Id).ToArray();

            return RedirectToAction(nameof(CategoryProducts));
        }

        public async Task<IActionResult> SaleProducts()
        {
            var products = await _unitOfWork.DiscountsDbStorage.GetProductsWithDiscountsAsync();

            TempData["searchingProductsId"] = products.Count() == 0 ? new int[1] { -1} : products.Select(x => x.Id).ToArray();

            return RedirectToAction(nameof(CategoryProducts));
        }

        [HttpPost]
        public async Task<IActionResult> SearchProducts(string searchingText)
        {
            if (searchingText.ToLower() == "акции")
            {
                return RedirectToAction(nameof(SaleProducts));
            }

            var products = await _unitOfWork.ProxyProductsDbStorage.GetAllAsync();

            var nameSortingProducts = products.Where(x => x.Name.ToLower().Contains(searchingText.ToLower())).ToList();
            var brandSortingProducts = products.Where(x => EnumHelper.GetDisplayName(x.Brand).ToLower().Contains(searchingText.ToLower())).ToList();
            var categorySortingProducts = products.Where(x => EnumHelper.GetDisplayName(x.Category).ToLower().Contains(searchingText.ToLower())).ToList();

            var sortingProducts = new List<Product>();
            sortingProducts.AddRange(brandSortingProducts);
            sortingProducts.AddRange(nameSortingProducts);
            sortingProducts.AddRange(categorySortingProducts);

            TempData["searchingProductsId"] = sortingProducts.Count() == 0 ? new int[1] { -1 } : sortingProducts.Distinct().Select(x => x.Id).ToArray();

            return RedirectToAction(nameof(CategoryProducts));
        }

    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/Basket/BasketViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DB.Models;
using OnlineShop.DB.Models.Interfaces;
using OnlineShop.DB.Patterns;
using OnlineShopWebApp.Helpers;
using OnlineShopWebApp.Models;
using ReturnTrue.AspNetCore.Identity.Anonymous;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace OnlineShopWebApp.Views.Shared.Components.Cart
{
    public class BasketViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<User> _userManager;
        private readonly IMapper _mapping;
        public BasketViewComponent(UserManager<User> userManager, IMapper mapping, IUnitOfWork unitOfWork)
        {
            _userManager = userManager;
            _mapping = mapping;
            _unitOfWork = unitOfWork;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userId = await GetUserId();

            var basketView = _mapping.Map<BasketViewModel>(await _unitOfWork.ProxyBasketDbStorage.TryGetExistingByUserIdAsync(userId));
            
            decimal productCounts = basketView?.Amount ?? 0;

            return View("Basket", productCounts);
        }

        public async Task<string> GetUserId()
        {
            var anonymousId = HttpContext.Features.Get<IAnonymousIdFeature>().AnonymousId;
            return User.Identity.IsAuthenticated ? (await _userManager.FindByNameAsync(User.Identity.Name)).Id : anonymousId;
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/Comparer/ComparerViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DB.Models;
using OnlineShop.DB.Models.Interfaces;
using OnlineShop.DB.Patterns;
using OnlineShopWebApp.Models;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace OnlineShopWebApp.Views.Shared.Components.Comparer
{
    public class ComparerViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<User> _userManager;
        public ComparerViewComponent(UserManager<User> userManager, IUnitOfWork unitOfWork)
        {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<ComparingProducts> products = null;
            if (User.Identity.Name != null)
            {
                var userId = (await _userManager.FindByNameAsync(User.Identity.Name))?.Id;
                products = userId == null ? null : await _unitOfWork.ComparingProductsDbStorage.GetAllByUserIdAsync(userId);
            }
            int productCounts = products?.Count ?? 0;
            return View("Comparer", productCounts);

        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/Favorites/FavoritesViewComponent.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DB.Models;
using OnlineShop.DB.Models.Interfaces;
using OnlineShop.DB.Patterns;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace OnlineShopWebApp.Views.Shared.Components.Favorites
{
    public class FavoritesViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<User> _userManager;

        public FavoritesViewComponent(UserManager<User> userManager, IUnitOfWork unitOfWork)
        {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {            
            if(User.Identity.IsAuthenticated)
            {
                var userId = (await _userManager.FindByNameAsync(User.Identity.Name)).Id;
                var favoriteCount = (await _unitOfWork.FavoriteProductsDbStorage.GetByUserIdAsync(userId))?.Products.Count ?? 0;
                return View("Favorites", favoriteCount);
            }
            return View("Favorites", 0);

        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/PersonalData/PersonalDataViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DB.Models;
using OnlineShop.DB.Models.Interfaces;
using OnlineShopWebApp.Models;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace OnlineShopWebApp.Views.Shared.Components.PersonalData
{
    public class PersonalDataViewComponent : ViewComponent
    {
        private readonly UserManager<User> _userManager;
        public PersonalDataViewComponent(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            return View("PersonalData", user);

        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/AddFeedbackModal.cshtml
@model AddFeedbackModel


<div class="modal" id="addFeedbackModal">
    <form role="form" method="post">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Ваш отзыв</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <div class="modal-body">
                    <div class="form-group form-inline">
                        <label for="name" class="col-2">Имя</label>
                        <div class="col-10">
                            <input asp-for="UserName" class="form-control w-100" id="name" placeholder="Ваше имя">
                        </div>
                        <div class="col-12">
                            <span asp-validation-for="UserName" style="color:red"></span>
                        </div>
                    </div>
                    <div class="form-group form-inline">
                        <label for="grade" class="col-2 control-label">Оценка</label>
                        <div class="rating-area col-10">
                            <input type="radio" id="star-5" asp-for="Grade" value="5">
                            <label for="star-5" title="Оценка «5»"></label>
                            <input type="radio" id="star-4" asp-for="Grade" value="4">
                            <label for="star-4" title="Оценка «4»"></label>
                            <input type="radio" id="star-3" asp-for="Grade" value="3">
                            <label for="star-3" title="Оценка «3»"></label>
                            <input type="radio" id="star-2" asp-for="Grade" value="2">
                            <label for="star-2" title="Оценка «2»"></label>
                            <input type="radio" id="star-1" asp-for="Grade" value="1">
                            <label for="star-1" title="Оценка «1»"></label>
                        </div>
                    </div>
                    <div class="form-group form-inline">
                        <label for="feedback" class="col-2">Отзыв</label>
                        <div class="col-10">
                            <textarea asp-for="Text" class="form-control w-100" id="feedback" placeholder="Оставьте отзыв"></textarea>
                        </div>
                        <div class="col-12">
                            <span asp-validation-for="Text" style="color:red"></span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input hidden="hidden" asp-for="Login" value="@Model.Login" />
                    <input hidden="hidden" asp-for="ProductId" value="@Model.ProductId" />
                    <button class="btn btn btn-success" type="submit" asp-area="" asp-controller="Product" asp-action="AddFeedback">Отправить</button>
                </div>
            </div>            
        </div>
    </form>
</div>

OnlineShop/OnlineShopWebApp/Views/Shared/Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        <div class="col-12 text-left small">
            &copy; 2023 - OnlineShopWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> | Продажа спортпита оптом со склада и в розницу. Спортивное питание BullBody - сеть магазинов спортивного питания!
        </div>
    </div>
</footer>

OnlineShop/OnlineShopWebApp/Views/Shared/Header.cshtml
<header>
    <nav style="display:block" class="border-secondary border navbar bg-light">
        <div class="row align-items-center">
            <div class="col-3 no-gutters">
                <div class="col-12">
                    <a class="navbar-brand" asp-area="" asp-action="Index" asp-controller="Home">
                        <img class="img-fluid" src="~/icons/Main.png">
                    </a>
                </div>
            </div>
            <div class="col-9">
                <div class="row justify-content-center align-items-center">
                    <div class="col-auto">
                        <form method="post" class="form-inline">
                            <input name="searchingText" style="width:440px" class="form-control" type="search" placeholder="Поиск">
                            <button asp-controller="Product" asp-action="SearchProducts" class="btn border-0" type="submit"><img src="/icons/search_icon.png" width="30" /></button>
                        </form>
                    </div>
                    @if (User.IsInRole(Constants.AdminRoleName) || User.IsInRole(Constants.ModeratorRoleName))
                    {
                        <div class="col-auto">
                            <a asp-controller="Order" asp-action="ClosedOrders" asp-area="Admin" role="button" class="btn btn-outline-dark">Администратор</a>
                        </div>
                    }
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <div class="col-auto">
                            <a asp-controller="UserEntering" asp-action="Login" asp-area="" role="button" class="btn border-0"><img src="~/icons/user_mini_icon.png" width="30" />Войти</a>
                        </div>
                    }
                    else
                    {
                        @await Component.InvokeAsync("PersonalData")
                    }
                    <div class="col-3 p-0">
                        <div class="row justify-content-end">
                            <div class="col-3 text-center">
                                @await Component.InvokeAsync("Favorites")
                            </div>
                            <div class="col-3 text-center">
                                @await Component.InvokeAsync("Comparer")
                            </div>
                            <div class="col-3 text-center">
                                @await Component.InvokeAsync("Basket")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>
@await Html.PartialAsync("NavigationMenu")

OnlineShop/OnlineShopWebApp/Views/Shared/NavigationMenu.cshtml
<div class="row align-items-center mb-4 border-1 border-light bg-danger sticky-top">
    <div class="col-8">
        <div class="row justify-content-between">
            <div class="col">
                <a onclick="this.blur()" role="button" class="btn btn-lg border-0" asp-area="" asp-controller="Product" asp-action="SaleProducts"><span style="color:white">АКЦИИ</span></a>
            </div>
            <div class="col">
                <div class="dropdown">
                    <button onclick="this.blur()" class="btn btn-lg border-0 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span style="color:white">СПОРТ</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        @foreach (var category in Enum.GetValues(typeof(ProductCategories)).Cast<ProductCategories>().ToList())
                        {
                            if(category == ProductCategories.None)
                            {
                                <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="CategoryProducts" asp-route-isAllListProducts="@true">Все товары</a>
                            }
                            else if (category.ToString().Contains("Sport"))
                            {
                                <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="CategoryProducts" asp-route-category="@category">@EnumHelper.GetDisplayName(category)</a>
                            }                            
                        }
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="dropdown">
                    <button onclick="this.blur()" class="btn btn-lg border-0 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span style="color:white">ЗДОРОВЫЕ ПЕРЕКУСЫ</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        @foreach (var category in Enum.GetValues(typeof(ProductCategories)).Cast<ProductCategories>().ToList())
                        {
                            if (category == ProductCategories.None)
                            {
                                <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="CategoryProducts" asp-route-isAllListProducts="@true">Все товары</a>
                            }
                            else if (category.ToString().Contains("HealthyFood"))
                            {
                                <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="CategoryProducts" asp-route-category="@category">@EnumHelper.GetDisplayName(category)</a>
                            }
                        }
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="dropdown">
                    <button onclick="this.blur()" class="btn btn-lg border-0 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span style="color:white">ВИТАМИНЫ</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="#">Товар 1</a>
                        <a class="dropdown-item" href="#">Товар 2</a>
                        <a class="dropdown-item" href="#">Товар 3</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="dropdown">
                    <button onclick="this.blur()" class="btn btn-lg border-0 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span style="color:white">ДОБАВКИ</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="#">Товар 1</a>
                        <a class="dropdown-item" href="#">Товар 2</a>
                        <a class="dropdown-item" href="#">Товар 3</a>
                    </div>
                </div>
            </div>
        </div>        
    </div>
    <div class="col-4 text-center">
        <a class="btn btn-lg border-0" role="button" asp-area="" asp-controller="Home" asp-action="Contacts">
            <img src="/icons/contact.png" />
            <span style="color:white">КОНТАКТЫ</span>
        </a>
    </div>
</div>

OnlineShop/OnlineShopWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@Constants.OnlineShopName</title>
    <link rel="shortcut icon" href="/icons/favicon.ico">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/myStyle.css" />    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body style="font-family:Bahnschrift">
    @await Html.PartialAsync("Header")
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await Html.PartialAsync("Footer")
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>